export const KENYA_COUNTIES: Record<string, string[]> = {
  "Baringo": ["Kabarnet", "Eldama Ravine", "Marigat"],
  "Bomet": ["Bomet", "Sotik"],
  "Bungoma": ["Bungoma", "Webuye", "Kimilili"],
  "Busia": ["Busia", "Malaba"],
  "Elgeyo-Marakwet": ["Iten", "Tambach"],
  "Embu": ["Embu", "Runyenjes"],
  "Garissa": ["Garissa", "Dadaab"],
  "Homa Bay": ["Homa Bay", "Mbita"],
  "Isiolo": ["Isiolo", "Merti"],
  "Kajiado": ["Kajiado", "Ongata Rongai", "Kitengela", "Ngong"],
  "Kakamega": ["Kakamega", "Mumias", "Lurambi"],
  "Kericho": ["Kericho", "Litein"],
  "Kiambu": ["Kiambu", "Thika", "Ruiru", "Kikuyu", "Juja"],
  "Kilifi": ["Kilifi", "Malindi", "Mtwapa"],
  "Kirinyaga": ["Kerugoya", "Kutus", "Sagana"],
  "Kisii": ["Kisii", "Ogembo"],
  "Kisumu": ["Kisumu", "Ahero", "Maseno"],
  "Kitui": ["Kitui", "Mwingi"],
  "Kwale": ["Kwale", "Diani Beach", "Ukunda"],
  "Laikipia": ["Nanyuki", "Nyahururu", "Rumuruti"],
  "Lamu": ["Lamu", "Mpeketoni"],
  "Machakos": ["Machakos", "Athi River"],
  "Makueni": ["Wote", "Makindu"],
  "Mandera": ["Mandera", "El Wak"],
  "Marsabit": ["Marsabit", "Moyale"],
  "Meru": ["Meru", "Maua"],
  "Migori": ["Migori", "Isebania"],
  "Mombasa": ["Mombasa Island", "Nyali", "Kisauni", "Likoni", "Changamwe"],
  "Murang'a": ["Murang'a", "Kenol"],
  "Nairobi": ["Nairobi CBD", "Westlands", "Kasarani", "Embakasi", "Lang'ata", "Dagoretti", "Kibra"],
  "Nakuru": ["Nakuru", "Naivasha", "Gilgil", "Molo"],
  "Nandi": ["Kapsabet", "Nandi Hills"],
  "Narok": ["Narok", "Kilgoris"],
  "Nyamira": ["Nyamira", "Keroka"],
  "Nyandarua": ["Ol Kalou", "Njabini"],
  "Nyeri": ["Nyeri", "Karatina", "Othaya"],
  "Samburu": ["Maralal", "Baragoi"],
  "Siaya": ["Siaya", "Bondo"],
  "Taita-Taveta": ["Voi", "Wundanyi", "Taveta"],
  "Tana River": ["Hola", "Garsen"],
  "Tharaka-Nithi": ["Chuka", "Marimanti"],
  "Trans Nzoia": ["Kitale", "Kimini"],
  "Turkana": ["Lodwar", "Kakuma"],
  "Uasin Gishu": ["Eldoret", "Burnt Forest"],
  "Vihiga": ["Vihiga", "Luanda"],
  "Wajir": ["Wajir", "Habaswein"],
  "West Pokot": ["Kapenguria", "Makutano"]
};